#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 <old_ip> <new_ip>"
    exit 1
fi

if [ -z "$2" ]; then
    echo "Usage: $0 <old_ip> <new_ip>"
    exit 1
fi

# Check if the IP is valid
if [[ ! $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid IP address"
    exit 1
fi

OLD_IP=${1//./\\.}
NEW_IP=${2//./\\.}

FILES=$(rg -l "$1")

for FILE in $FILES; do
    sed -i "s/$OLD_IP/$NEW_IP/g" "$FILE"
    tf apply -chdir "$(dirname $FILE)"
done
